// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PluginVidaExtra","status":false,"description":"plugin del proyecto Vida Extra","parameters":{}},
{"name":"TextPicture","status":false,"description":"Displays text as a picture.","parameters":{}}
];
